version: "3.9"

x-django-default: &django-default
    env_file:
        - ./.env
    volumes:
        - .:/app

services:
    db:
        image: postgres:13.1
        env_file:
            - ./.env
        volumes:
            - VRPTW_db_data:/var/lib/postgresql/data/

    redis:
        image: redis:5.0.10
        container_name: redis

    django:
        <<: *django-default
        build:
            context: .
            dockerfile: docker/Dockerfile.django
        command: ./docker/django_setup.sh
        ports:
            - "8000:8000"
            - "220:22"
        depends_on:
            - db

    vue:
        image: node:14.13.0-stretch
        command: ./docker/vue_setup.sh
        working_dir: /app
        volumes:
            - .:/app
        ports:
            - "8080:8080"
        depends_on:
            - django

volumes:
    VRPTW_db_data:
