FROM python:3.6.9

RUN apt update -y && \
    apt install -yqq python-ldap libldap2-dev libsasl2-dev libssl-dev python3.7-dev redis ssh

WORKDIR /app

COPY Pipfile* ./

RUN pip install pipenv
RUN pipenv sync --dev