# Generated by Django 3.2.11 on 2022-01-04 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientDistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField()),
                ('time', models.IntegerField()),
                ('client1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client1', to='vue_api.client')),
                ('client2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client2', to='vue_api.client')),
            ],
        ),
    ]
