# Generated by Django 3.2.11 on 2022-01-04 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vue_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='info',
            new_name='name',
        ),
    ]
