# Generated by Django 3.2.11 on 2022-01-04 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vue_api', '0002_rename_info_client_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
