# Generated by Django 3.2.11 on 2022-01-04 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vue_api', '0004_alter_client_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
