# Generated by Django 3.2.11 on 2022-01-07 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vue_api', '0007_result_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultDistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demand', models.IntegerField()),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('truck', models.IntegerField(blank=True, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vue_api.client')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vue_api.result')),
            ],
        ),
    ]
