# Generated by Django 3.2.11 on 2022-01-07 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vue_api', '0008_resultdistance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResultDistance',
            new_name='ResultClient',
        ),
    ]
