# Generated by Django 3.2.11 on 2022-01-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vue_api', '0010_alter_resultclient_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cad', models.IntegerField()),
                ('maxint', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='clientdistance',
            name='cost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='clientdistance',
            name='time',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='result',
            name='cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resultclient',
            name='demand',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='resultclient',
            name='end',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='resultclient',
            name='start',
            field=models.FloatField(),
        ),
    ]
