# Generated by Django 3.2.11 on 2022-01-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vue_api', '0011_auto_20220109_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='globalvalues',
            old_name='cad',
            new_name='tabu_term',
        ),
        migrations.AddField(
            model_name='resultclient',
            name='start_of_service',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
